services:
  # Base de Datos para SonarQube
  db-sonarqube:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jenkins-net

  # Servidor SonarQube
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-server
    depends_on:
      - db-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonarqube:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - jenkins-net

  # Tu Jenkins (Mantenemos tu ruta ./jenkins_home)
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home # Mantiene tus datos antiguos
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

  # Tu App de Python
  app-goles:
    build: .
    image: fase1:latest
    container_name: app-goles-container
    stdin_open: true
    tty: true
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
